createPostgresqlSecret: true # create the postgresql secret in Sonarqube chart, outside of the postgresql chart.

# If createPostgresqlSecret is `false` then existingSecret is the name of the secret that contains the postgresql-password you are providing.

## Configuration values for postgresql dependency
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
  postgresqlUsername: "myUser"
  postgresqlDatabase: "myDB"
  existingSecret: my-postgresql-secret # This is the full name of the secret that will be created 
  secretKey: postgresql-password
