createPostgresqlSecret: true # create the postgresql secret in Sonarqube chart, outside of the postgresql chart.

## Configuration values for postgresql dependency
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
  postgresqlUsername: "sonarUser"
  postgresqlPassword: ""   
  postgresqlDatabase: "sonarDB"
  existingSecret: sonar-postgresql # This is the full name of the secret that will be created 
  secretKey: postgresql-password
