{{- if .Values.createPostgresqlSecret -}} # if .Values.createPostgresqlSecret is true then this file will be generated.
{{- $relname := printf "%s-%s" .Release.Name "postgresql" -}} # this will create the variable $relname with the value <release-name>-postgresql.
apiVersion: v1
kind: Secret
metadata:
  name: {{- if .Values.postgresql.existingSecret }} {{ .Values.postgresql.existingSecret }} {{ else }} {{ $relname }} {{- end }} # if existingSecret has been set use that name else use variable $relname
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Release.IsUpgrade }} # Performing a "helm upgrade" then go in here 
  # check to see if secret already exists in namespace.
    {{- if (index (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret ) ) }}
      postgresql-password: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret ).data "postgresql-password" }}
    {{ else }}
    # if a secret isn't found when perfroming an upgrade create a new secret.
        {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
        postgresql-password: {{ $postgresRandomPassword }}
    {{- end }}
  {{ else }}
  # Perform normal install operation
      {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
      postgresql-password: {{ $postgresRandomPassword }}
  {{ end }}
{{- end }}
